# Generated by Django 5.1.5 on 2025-01-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='id_trabajador',
            new_name='id',
        ),
    ]
