# Generated by Django 5.1.5 on 2025-01-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_permiso_permisogrupo_permisosusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('permisos', models.ManyToManyField(through='libreria.PermisosUsuario', to='libreria.permiso')),
            ],
        ),
        migrations.AlterField(
            model_name='permisosusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.usuarioregistrado'),
        ),
        migrations.AlterUniqueTogether(
            name='permisosusuario',
            unique_together={('usuario', 'permiso')},
        ),
    ]
