# Generated by Django 5.1.5 on 2025-01-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_usuarioregistrado_alter_permisosusuario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasSupervisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasTrabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.empresas')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.usuarioregistrado')),
            ],
            options={
                'unique_together': {('empresa', 'trabajador')},
            },
        ),
        migrations.CreateModel(
            name='PermisosSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('permisos', models.ManyToManyField(through='libreria.PermisosSupervisor', to='libreria.permiso')),
            ],
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AddField(
            model_name='empresas',
            name='trabajadores',
            field=models.ManyToManyField(through='libreria.EmpresasTrabajadores', to='libreria.usuarioregistrado'),
        ),
        migrations.AddField(
            model_name='permisossupervisor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.supervisorregistrado'),
        ),
        migrations.AddField(
            model_name='empresassupervisores',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.supervisorregistrado'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='supervisores',
            field=models.ManyToManyField(through='libreria.EmpresasSupervisores', to='libreria.supervisorregistrado'),
        ),
        migrations.AlterUniqueTogether(
            name='permisossupervisor',
            unique_together={('usuario', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='empresassupervisores',
            unique_together={('empresa', 'supervisor')},
        ),
    ]
