# Generated by Django 5.1.5 on 2025-01-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_trabajador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisossupervisor',
            old_name='usuario',
            new_name='supervisor',
        ),
        migrations.AlterUniqueTogether(
            name='permisossupervisor',
            unique_together={('supervisor', 'permiso')},
        ),
    ]
